-- MySQL Script generated by MySQL Workbench
-- Wed Aug 24 21:18:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema qlct
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qlct
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qlct` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `qlct` ;

-- -----------------------------------------------------
-- Table `qlct`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qlct`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phonenumber` VARCHAR(12) NOT NULL,
  `avt` VARCHAR(100) NULL DEFAULT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phonenumber_UNIQUE` (`phonenumber` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qlct`.`earnings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qlct`.`earnings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `currency` DECIMAL(10,0) NOT NULL,
  `details` VARCHAR(200) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_id_user_ear`
    FOREIGN KEY (`id_user`)
    REFERENCES `qlct`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qlct`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qlct`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qlct`.`earnings_gr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qlct`.`earnings_gr` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `standby_state` TINYINT NOT NULL,
  `id_ear` INT NOT NULL,
  `id_gr` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_gr_idx` (`id_gr` ASC) VISIBLE,
  INDEX `fk_id_ear_idx` (`id_ear` ASC) VISIBLE,
  CONSTRAINT `fk_id_ear`
    FOREIGN KEY (`id_ear`)
    REFERENCES `qlct`.`earnings` (`id`),
  CONSTRAINT `fk_id_gr`
    FOREIGN KEY (`id_gr`)
    REFERENCES `qlct`.`group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qlct`.`expenditures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qlct`.`expenditures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` DATETIME NOT NULL,
  `currency` DECIMAL(10,0) NOT NULL,
  `details` VARCHAR(200) NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_user_exp_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_id_user_exp`
    FOREIGN KEY (`id_user`)
    REFERENCES `qlct`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qlct`.`expenditures_gr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qlct`.`expenditures_gr` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `standby_state` TINYINT NOT NULL,
  `id_gr` INT NOT NULL,
  `id_exp` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_exp_idx` (`id_exp` ASC) VISIBLE,
  INDEX `fk_id_group_idx` (`id_gr` ASC) VISIBLE,
  CONSTRAINT `fk_id_exp`
    FOREIGN KEY (`id_exp`)
    REFERENCES `qlct`.`expenditures` (`id`),
  CONSTRAINT `fk_id_group`
    FOREIGN KEY (`id_gr`)
    REFERENCES `qlct`.`group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `qlct`.`member_gr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qlct`.`member_gr` (
  `id` INT NOT NULL,
  `id_gr` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_id_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_gr_id_idx` (`id_gr` ASC) VISIBLE,
  CONSTRAINT `fk_gr_id`
    FOREIGN KEY (`id_gr`)
    REFERENCES `qlct`.`group` (`id`),
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`id_user`)
    REFERENCES `qlct`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
